name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      
      - run: ls

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.18'
          # mdbook-version: 'latest'
          
      - name: Install a binary from GitHub releases
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with: # Install mdbook-admonish binary from GitHub releases
          repo: tommilligan/mdbook-admonish   
          tag: v1.7.0  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: mdbook build
      
      - run: ls

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_empty_commit: true
          publish_dir: ./autogenerated-html
          cname: www.vault53.de
